// Generated by scripts/build-service-worker.mjs. Do not edit manually.
const CACHE="rule-finder-8d36e29dedd6";
const APP_SHELL=["./","./index.html","./favicon.svg","./manifest.webmanifest","./icons/app-icon-192.png","./icons/app-icon-512.png","./icons/app-icon-maskable-512.png","./src/styles.css","./src/app.js","./src/data/rules.js","./src/data/battlefield-fundamentals.js","./src/data/scenarios.js","./src/data/datasheet-explainers.js","./src/data/active-game.js","./src/data/faction-rules.js","./src/data/search-index.js","./src/data/legacy-content.js","./src/lib/rule-finder.js","./src/lib/active-game.js","./src/lib/game-reference.js","./src/lib/storage.js","./src/lib/router.js","./src/lib/search-query.js","./src/lib/catalog-search.js","./src/lib/html.js","./src/lib/voice-search.js","./src/lib/source-verification.js","./src/views/cards.js","./src/views/game-reference.js","./src/views/home-search.js","./src/views/unit-detail.js","./src/views/reference-details.js","./src/views/source-verification.js","./src/controllers/active-game.js","./src/controllers/app-updates.js","./src/controllers/reference-dialog.js","./src/controllers/search-state.js","./src/controllers/unit-directory.js","./src/data/unit-directory.js","./src/data/detachments.js","./src/data/detachment-rules.js","./src/data/detachment-rule-details.js"];

self.addEventListener("install",(event)=>{
  event.waitUntil(caches.open(CACHE).then((cache)=>cache.addAll(APP_SHELL)));
});

self.addEventListener("activate",(event)=>{
  event.waitUntil(caches.keys()
    .then((keys)=>Promise.all(keys.filter((key)=>key.startsWith("rule-finder-")&&key!==CACHE).map((key)=>caches.delete(key))))
    .then(()=>self.clients.claim()));
});

self.addEventListener("message",(event)=>{
  if(event.data?.type==="SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("fetch",(event)=>{
  const request=event.request;
  if(request.method!=="GET"||new URL(request.url).origin!==self.location.origin) return;
  if(request.mode==="navigate"){
    event.respondWith((async()=>{
      try{
        const response=await fetch(request);
        const contentType=response.headers.get("content-type")??"";
        if(response.ok&&contentType.includes("text/html")){
          const cache=await caches.open(CACHE);
          await cache.put("./index.html",response.clone());
        }
        return response;
      }catch{
        return await caches.match("./index.html")??new Response("Offline",{status:503,headers:{"Content-Type":"text/plain; charset=utf-8"}});
      }
    })());
    return;
  }
  event.respondWith((async()=>{
    const cached=await caches.match(request);
    if(cached) return cached;
    const response=await fetch(request);
    if(response.ok){
      const cache=await caches.open(CACHE);
      await cache.put(request,response.clone());
    }
    return response;
  })());
});
